apiVersion: v1
kind: Service
metadata:
  labels:
    app: lb-app-projetofiap
  name: lb-app-projetofiap
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: projetofiap-deployment
  type: LoadBalancer