apiVersion: v1
kind: Pod
metadata: 
  name: projeto-fiap-db
  labels: 
    app: projeto-fiap-db
spec:
  containers:
    - name: db
      image: postgres
      args:
        - -c
        - max_connections=1000
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: opaque-postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opaque-postgres-secret
              key: POSTGRES_PASSWORD
      livenessProbe:
        exec:
          command:
            - ls
            - /var/lib/postgresql/data
        initialDelaySeconds: 10
        periodSeconds: 30